### PR TITLE
Set TCP_KEEPALIVE socket option to all sockets to fix issue-100

### PR DESCRIPTION
**Pull request by vbanthia**
Issue - https://github.com/openstf/stf/issues/100

### CODE REVIEW

**Comment by sorccu** [comment]
Nice, but it seems kind of annoying to have to call a separate method every time you want to create a socket. I would perhaps prefer something like this:

```js
var push = zmqutil.socket('push')
```

instead of

```js
var push = zmq.socket('push')
zmqutil.setTCPSocketOpts(push)
```

and then zmqutil would be:

```js
module.exports.socket = function() {
  var sock = zmq.socket.apply(zmq, arguments)
  sock.setsockopt(zmq.ZMQ_TCP_KEEPALIVE, 1)
  sock.setsockopt(zmq.ZMQ_TCP_KEEPALIVE_IDLE, 300000)
  return sock
}
```

**Comment by vbanthia** [comment]
True. Will change it.

**Comment by vbanthia** [comment]
done.

**Comment by sorccu** [comment]
Looks good to me, but I'll have to run it first to make sure things still work. Will merge tonight.

**Comment by sorccu** [comment]
One thing: there may be some unused `require('zmq')` calls left behind now since almost everything uses zmqutil.

**Comment by vbanthia** [comment]
Thanks for the review, and yeah please check this in your environment too. Its working okay on mac.

**Comment by sorccu** [comment]
Thanks!

**Comment by sorccu** [comment]
Turns out this breaks at least on latest stable CoreOS when using `--net host` with docker. We also have a separate report of the same thing in #139. It looks like the value for ZMQ_TCP_KEEPALIVE_IDLE doesn't make sense, but pending further investigation I have simply made the keepalive options optional in 8e8f2d17b7.

Now you have to export or set environment variables to get the functionality:

```
ZMQ_TCP_KEEPALIVE=1 ZMQ_TCP_KEEPALIVE_IDLE=30000 stf local
```

or

```
docker run \
  -e ZMQ_TCP_KEEPALIVE_IDLE=1 \
  -e ZMQ_TCP_KEEPALIVE_IDLE=30000 \
  openstf/stf:latest stf triproxy ...
```

**Comment by vbanthia** [comment]
Sorry, I could not test this PR in CoreOS. I need to make a CoreOS dev environment.

The reason, I added ZMQ_TCP_KEEPALIVE_IDLE option is that default KEEP_IDLE (*Amount of time, in milliseconds, that the (TCP) connection must be idle before sending keepalive probes*) option value for mac or some linux OS such as CentOS is 2hrs. Which means TCP_KEEP_ALIVE will start probing after 2hrs. And in my case connection was dying after 20mins, so I set it to 5mins.

And thanks for making these param optional.

**Comment by sorccu** [comment]
Yeah, but it looks like ZMQ_TCP_KEEPALIVE_IDLE actually does this:

> ZMQ_TCP_KEEPALIVE_IDLE: Override TCP_KEEPCNT (or TCP_KEEPALIVE on some OS)

and then

> TCP_KEEPCNT (since Linux 2.4) The maximum number of keepalive probes TCP should send before dropping the connection. This option should not be used in code intended to be portable.

That seems kind of different than we want. Looks like these seems more appropriate:

> TCP_KEEPIDLE (since Linux 2.4)
>        The time (in seconds) the connection needs to remain idle
>        before TCP starts sending keepalive probes, if the socket
>        option SO_KEEPALIVE has been set on this socket.  This option
>        should not be used in code intended to be portable.
> 
> TCP_KEEPINTVL (since Linux 2.4)
>        The time (in seconds) between individual keepalive probes.
>        This option should not be used in code intended to be
>        portable.

**Comment by vbanthia** [comment]
ZeroMQ documentation looks a bit weird. Because in source code it is setting SO_KEEPIDLE option on ZMQ_TCP_KEEPALIVE_IDLE and for TCP_KEEPCNT they have ZMQ_HAVE_TCP_KEEPCNT

https://github.com/zeromq/libzmq/blob/master/src/tcp.cpp#L131-L135

```
#ifdef ZMQ_HAVE_TCP_KEEPIDLE
        if (keepalive_idle_ != -1) {
            int rc = setsockopt (s_, IPPROTO_TCP, TCP_KEEPIDLE, &keepalive_idle_, sizeof (int));
            errno_assert (rc == 0);
        }
```

**Comment by sorccu** [comment]
Yeah, seems to be that way: https://github.com/zeromq/libzmq/commit/d9f32611adcb2a3c2c46748b16056def10391192

Either way, it looks the the values for `setsockopt()` are supposed to be seconds, not milliseconds.

**Pull request merged**
