### PR TITLE
Add Simplified Chinese translations

### PR DESCRIPTION
**Pull request by buaawp**
Add Simplified Chinese translations.

### CODE REVIEW

**Comment by codeskyblue** [comment]
👍

**Comment by jonqchk** [comment]
Hi buaawp, have you check the functionality for this PR? As I know, STF use Transifex for the Localization of different countries, so I am not sure the files you changed is generated by the Transifex client and works well?

**Comment by gunta** [comment]
Yes, please translate from https://www.transifex.com/openstf/stf/dashboard/ if possible.

**Comment by buaawp** [comment]
Ok, I will do that in transifex.

**Comment by jonqchk** [comment]
yes, I have a look at your translation, it seems well, many words were translated clearly. hope you can complement the simple Chinese translation in Transifex and then merge in code. I also wait it. :+1: )

**Pull request closed without merging**
