### PR TITLE
[#460][#349][#19] Potential fix - Enable Screenshots functionality

### PR DESCRIPTION
**Pull request by lukzeg**
Basing on commented functionality and mostly the problem with issues mentioned in https://github.com/openstf/stf/issues/460 and https://github.com/openstf/stf/issues/349 I noticed that mostly my problem was connected with not using imagemagick. Mostly I had problem with proper converting bitmap which was collected from blob.
After changing:
var gm = require('gm')
to:
var gm = require('gm').subClass({imageMagick: true})
Screenshots bitmaps are properly displayed on stf screenshot div.

### CODE REVIEW

**Comment by lukzeg** [comment]
There is one dependency which will need to be added, need of installation of imagemagick.

**Comment by sorccu** [comment]
I don't want to depend on imagemagick. I'm not convinced that this is the real reason. It's more likely a timing issue (e.g. reading a stream too late), and using imagemagick just happens to change the timing.

Most likely not merging unless some kind of proof is provided.

**Comment by lukzeg** [comment]
Hi Simo, 

I made small investigation. Without using : 
var gm = require('gm').subClass({imageMagick: true})

http://aheckmann.github.io/gm/docs.html

I receive

 Error: Command failed: gm convert: No decode delegate for this image format (/tmp/gmYAAOaw).

    at ChildProcess.onExit (/home/luze/stf/stf/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Socket.<anonymous> (internal/child_process.js:351:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:497:12) code: 1, signal: null }

Mostly looks like gm nodejs module have problem with converting jpg images stored in s/blob.

To reproduce this error you can add in:
lib/units/storage/plugins/image/task/transform.js

var gm = require('gm')
var Promise = require('bluebird')
var logger = require('../../../../../util/logger')
var request = require('request').defaults({ encoding: null });;

module.exports = function(stream, options) {
 var log = logger.createLogger('storage:plugins:image:task:transform.js')
 log.info('luze dupa')
 log.info(stream)
  return new Promise(function(resolve, reject) {
    log.info("imagemagick")
    var test = JSON.parse(JSON.stringify(stream))
    log.info(JSON.stringify(test.uri))
    log.info("imagemagick will continue")

    var url = test.uri.href;
    gm(request(url)).write('/tmp/reformat.jpg', function (err) {
      if (!err) {log.info('done')}
      else {log.info(err)};
   })
   
   var transform = gm(stream)
   ....

The solution works on my machine.

**Comment by sorccu** [comment]
Perhaps your gm is missing jpeg support for some reason? Are you able to use ‘gm convert’ on the command line?

**Comment by lukzeg** [comment]
Hmm, thats true. gm convert ad hoc on my machine did not support jpg.

luze@luze-001:~/stf/stf$ gm convert -list format | grep JPG
luze@luze-001:~/stf/stf$ gm convert -size 120x120 ~/Desktop/0657049c0062100d.jpg  -resize 120x120 +profile "*" thumbail.jpg
gm convert: No decode delegate for this image format (/home/luze/Desktop/0657049c0062100d.jpg).
but imagemagick it is.

So mostly looks like add hoc, when we rebuild stf, gm is not supporting jpg.

**Comment by lukzeg** [comment]
There is a workaround for not using installed local imagemagick. I found this solution:
https://stackoverflow.com/questions/16094875/how-do-i-configure-a-jpeg-delegate-for-graphicsmagick
`$ cd ~/source
$ wget http://www.ijg.org/files/jpegsrc.v6b.tar.gz
$ tar -xzvf jpegsrc.v6b.tar.gz
$ cd jpeg-6b
$ ./configure
$ make
$ sudo make install

$ cd ~/source
$ wget ftp://ftp.graphicsmagick.org/pub/GraphicsMagick/1.3/GraphicsMagick-1.3.18.tar.xz
$ tar -xJvf GraphicsMagick-1.3.18.tar.xz
$ cd GraphicsMagick-1.3.18
$ ./configure
$ make
$ sudo make install

$ npm install gm`

After installing jpg-6b as well rebuilding GraphicsMagick and installation one more time gm, my gm is recognizing JPG format.

**Comment by sorccu** [comment]
Good to know for reference, but I think it may just be an issue on your computer. On my mac and in our Alpine Linux based docker images, gm from the package manager contains JPEG support by default.

How did you originally install gm?

**Comment by lukzeg** [comment]
The gm is installed locally during building process. 
`
npm install
`
when is downloading needed modules from package.json. I'm not doing anything else. 

I'm working at:
` 
lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
`

**Comment by sorccu** [comment]
Yes but I meant how did you install GraphicsMagick? With `apt-get`?

**Comment by lukzeg** [comment]
If I good remember I downloaded  sources from:
https://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/1.3.26/

and I created graphicsmagick from source.

**Comment by sorccu** [comment]
I see, that would probably be the cause then. Package managers include some basic functionality by default.

I'll close this issue now, doesn't seem like there's a need for this change.

**Comment by lukzeg** [comment]
Thank you for your patience @sorccu

**Pull request closed without merging**
