### PR TITLE
Add the button to change privilege

### PR DESCRIPTION
**Pull request by att55**
Hi,

"Group feature" was great work!
https://github.com/openstf/stf/pull/1056

But, I notice there isn't the component to change users privilege from UI.
I think this function is needed because users can not change privileges except Data Explorer of rethinkdb.

スクリーンショット 2020-06-29 22 32 15

### CODE REVIEW

**Comment by koral--** [comment]
@denis99999 @pcrepieux please you take a look.

**Comment by luoxi001713** [comment]
good feature, I really want to use this to change user privilege, appreciate to merge to master.

**Comment by denis99999** [comment]
Hi @att55 ,

Thanks for  the congratulations!

Regarding your PR, respect for the effort, but I'm sorry this is however not acceptable because it introduces consistency issues, semantics issues, functional issues as well as a little exception at runtime (i.e. it does not matter but you simply forgot to return the `stats` object at line `980` of `api.js` file), let me explain briefly.

In short, the admin role has been introduced mainly to serve the Group feature in which users, groups and devices are linked together with the requirement that there is only one administrator with a determined semantic, it means in particular it is not enough to simply modify the privilege property of a user in the STF database to change his role in a consistent way, it is much more complicated than that, and it is no coincidence that the modification of this property is also not authorized by the API even for the administrator user.

As explained in the documentation, remember that admin user and the root standard group are built-in objects linked together and they have to be specified at database creation or at database migration step if they don't exist yet (cf. #1249), so in your case you have if possible to recreate the STF database providing the expecting information.

Nevertheless, I understand your need to be able to assign the admin role to another user either because the STF database has been created in error using the default credentials, or because later it becomes a necessity. The first case as already said is treated by the recreation of the STF database, the second one in my mind has to be treated by the updating of the database customizing the actual migration process, I will take a deep look on that as soon as possible because you are not the first to raise this problem!

**Comment by att55** [comment]
@luoxi001713 Thank you for your comment ! 😄

**Comment by luoxi001713** [comment]
> @luoxi001713 Thank you for your comment ! 😄

ahah, but this is not approved, sad...

**Comment by att55** [comment]
@denis99999 Thank you for your review, I understood your explanation.

> I will take a deep look on that as soon as possible because you are not the first to raise this problem!

All right, I'm expecting this development! So, should I close this PR ?

**Comment by att55** [comment]
@luoxi001713 yeah, but he said as below.

> I will take a deep look on that as soon as possible because you are not the first to raise this problem!

Let's anticipate this future development.

**Comment by denis99999** [comment]
@att55 , yes you can close it!

**Comment by att55** [comment]
@denis99999 ok, I will close 👌

**Pull request closed without merging**
