### PR TITLE
Use 'ps -lef' instead of 'ps' to list Pids on Android 8.x

### PR DESCRIPTION
**Pull request by thinkhy**
Since Android 8.0 official version, 'ps' command is not workable to list process list. We should use 'ps -lef' instead on Android 8.0 and Android 8.1, so I attempt to fix the problem in lib/util/devutil.js.

### CODE REVIEW

**Comment by sorccu** [comment]
Can you describe how you found out about this issue? Did it break something? Also, possible to see output of the old & new command on those android versions?

**Comment by thinkhy** [comment]
I first found this issue in my scaffolding code for test automation, I intended to kill the process of uiautomator but it didn't work on Android 8.x, then I found the same issue on STF.

I will paste the output of the old&new command on devices of Pixel2(Android 8.0), Huawei Mate 10(Android 8.0), XiaoMi Mix2(Android 8.0) and OPPO R11plus(Android 8.1).

**Comment by thinkhy** [comment]
@sorccu I've tried out both the commands  "ps" and "ps -lef" on 7 devices from Android 7.0 to 8.1, covering 6 leading mobile brands:


### Nexus 6P, Android 8.1

```shell

ps

USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME                       
shell        28030 21619   10488   1936 0          75bb676f20 R ps

```


```shell

ps -lef

UID            PID  PPID C STIME TTY          TIME CMD
root             1     0 0 17:34:26 ?     00:00:33 init
root             2     0 0 17:34:26 ?     00:00:17 [kthreadd]
root             3     2 8 17:34:26 ?      4-07:08:50 [ksoftirqd/0]
root             5     2 0 17:34:26 ?     00:16:54 [kworker/0:0H]
root             6     2 0 17:34:26 ?     00:00:01 [kworker/u16:0]
root             7     2 0 17:34:26 ?     00:00:43 [migration/0]
root             8     2 1 17:34:26 ?     18:18:30 [rcuc/0]
root             9     2 0 17:34:26 ?     00:00:00 [rcub/0]
root            10     2 8 17:34:26 ?      4-07:26:33 [rcu_preempt]
root            11     2 0 17:34:26 ?     00:00:00 [rcu_bh]
root            12     2 0 17:34:26 ?     00:00:01 [rcu_sched]
... ...
```

```shell
ps -lef|grep stf
u0_a98        9132   613 0 17:42:39 ?     00:09:30 jp.co.cyberagent.stf
shell        16648 21619 0 21:22:36 pts/0 00:00:01 stf.agent
shell        28078 21619 3 19:44:20 pts/4 00:00:00 sh -c ps -lef|grep stf
shell        28081 28078 4 19:44:20 pts/4 00:00:00 grep stf
```

-----------------------------------------------------------------------------------------

### Pixel2, Android 8.1

```shell
ps
USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME                       
shell        16238   711   10544   1952 0          7679407ea4 R ps
```

```shell
ps -elf
USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME                       
shell        16238   711   10544   1952 0          7679407ea4 R ps
```

```shell
ps -lef
UID            PID  PPID C STIME TTY          TIME CMD
root             1     0 0 21:33:40 ?     00:00:33 init
root             2     0 0 21:33:40 ?     00:00:21 [kthreadd]
root             3     2 1 21:33:40 ?     01:18:14 [ksoftirqd/0]
root             5     2 0 21:33:40 ?     00:00:00 [kworker/0:0H]
root             6     2 0 21:33:40 ?     00:00:01 [kworker/u8:0]
root             7     2 0 21:33:40 ?     00:17:35 [rcu_preempt]
root             8     2 0 21:33:40 ?     00:00:20 [rcu_sched]
root             9     2 0 21:33:40 ?     00:00:00 [rcu_bh]
root            10     2 0 21:33:40 ?     00:01:45 [rcuc/0]
root            11     2 0 21:33:40 ?     00:00:00 [rcub/0]
root            12     2 0 21:33:40 ?     00:00:01 [migration/0]
... ...
```

```shell
ps -lef|grep stf
shell         2535   711 0 21:34:34 pts/0 00:00:00 stf.agent
u0_a545       2614   651 0 21:34:35 ?     00:00:21 jp.co.cyberagent.stf
shell        16257   711 3 19:45:47 pts/4 00:00:00 sh -c ps -lef|grep stf
shell        16260 16257 3 19:45:47 pts/4 00:00:00 grep stf
```

### Oppo R11s, Android 8.1

```shell
ps
USER           PID  PPID	FRZ      VSZ    RSS WCHAN            ADDR S NAME                       
shell        24566 23818	efg    11028   2048 0          7d4f679120 R ps
```

```shell
ps -elf
UID            PID  PPID	FRZ  C STIME TTY          TIME CMD
root             1     0	efg  0 15:02:13 ?     00:00:26 init
root             2     0	efg  0 15:02:13 ?     00:00:00 [kthreadd]
root             3     2	efg  1 15:02:13 ?     01:40:30 [ksoftirqd/0]
root             7     2	efg  0 15:02:13 ?     00:07:50 [rcu_preempt]
root             8     2	efg  0 15:02:13 ?     00:00:35 [rcu_sched]
root             9     2	efg  0 15:02:13 ?     00:00:00 [rcu_bh]
root            10     2	efg  0 15:02:13 ?     00:10:50 [rcuop/0]
root            11     2	efg  0 15:02:13 ?     00:00:28 [rcuos/0]
... ...
```

```shell
ps -elf|grep stf

u0_a152      20697  1260	efg  0 18:48:23 ?     00:00:00 jp.co.cyberagent.stf
shell        23990 23818	efg  0 09:56:42 pts/0 00:00:01 stf.agent
shell        24579 23818	efg  2 19:48:19 pts/4 00:00:00 sh -c ps -lef|grep stf
shell        24582 24579	efg  1 19:48:19 pts/4 00:00:00 grep stf
```

### Huawei Mate10, Android 8.0

```shell
ps
USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME                       
shell        11256   722   10236   2044 0          77378038d0 R ps
```

```shell
ps -elf
UID            PID  PPID C STIME TTY          TIME CMD
root             1     0 0 21:34:57 ?     00:01:43 init
root             2     0 0 21:34:57 ?     00:00:02 [kthreadd]
root             3     2 0 21:34:57 ?     00:05:52 [ksoftirqd/0]
root             5     2 0 21:34:57 ?     00:00:00 [kworker/0:0H]
root             7     2 1 21:34:57 ?     01:13:23 [rcu_preempt]
root             8     2 0 21:34:57 ?     00:00:32 [rcu_sched]
root             9     2 0 21:34:57 ?     00:00:00 [rcu_bh]
root            10     2 0 21:34:57 ?     00:00:08 [migration/0]
root            11     2 0 21:34:57 ?     00:00:00 [pid_iostats_upd]
root            12     2 0 21:34:57 ?     00:00:07 [migration/1]
root            13     2 0 21:34:57 ?     00:02:52 [ksoftirqd/1]
root            15     2 0 21:34:57 ?     00:00:00 [kworker/1:0H]
... ...

```

```shell
ps -elf|grep stf

shell         3235   722 0 21:35:13 pts/0 00:00:01 stf.agent
u0_a342       3550   514 0 21:35:14 ?     00:00:45 jp.co.cyberagent.stf
shell        11261   722 0 20:03:39 pts/4 00:00:00 sh -c ps -lef|grep stf
shell        11264 11261 1 20:03:39 pts/4 00:00:00 grep stf
```

### XiaoMi Mi 6, Android 8.0

```shell
USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME                       
shell        15491  1137   10204   2056 0          7f8007a898 R ps
```

```shell
ps -elf
UID            PID  PPID C STIME TTY          TIME CMD
root             1     0 0 03:08:24 ?     00:00:21 init
root             2     0 0 03:08:24 ?     00:00:00 [kthreadd]
root             3     2 0 03:08:24 ?     00:03:52 [ksoftirqd/0]
root             7     2 0 03:08:24 ?     00:00:26 [rcu_preempt]
root             8     2 0 03:08:24 ?     00:00:00 [rcu_sched]
root             9     2 0 03:08:24 ?     00:00:00 [rcu_bh]
root            10     2 0 03:08:24 ?     00:00:38 [rcuop/0]
root            11     2 0 03:08:24 ?     00:00:00 [rcuos/0]
root            12     2 0 03:08:24 ?     00:00:00 [rcuob/0]
... ...

```

```shell
ps -elf|grep stf

shell         3936  1137 0 03:09:07 pts/0 00:00:00 stf.agent
u0_a149       4086   629 0 03:09:08 ?     00:00:00 jp.co.cyberagent.stf
shell        15502  1137 4 20:15:11 pts/4 00:00:00 sh -c ps -elf|grep stf
shell        15505 15502 9 20:15:11 pts/4 00:00:00 grep stf
```

### Vivo X9, Android 7.1.2

```shell
ps
USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
root      1     0     17132  2604  SyS_epoll_ 0000000000 S /init
root      2     0     0      0       kthreadd 0000000000 S kthreadd
root      3     2     0      0     smpboot_th 0000000000 S ksoftirqd/0
root      5     2     0      0     worker_thr 0000000000 S kworker/0:0H
root      7     2     0      0     rcu_gp_kth 0000000000 S rcu_preempt
root      8     2     0      0     rcu_gp_kth 0000000000 S rcu_sched
root      9     2     0      0     rcu_gp_kth 0000000000 S rcu_bh
root      10    2     0      0     nocb_leade 0000000000 S rcuop/0
root      11    2     0      0     nocb_leade 0000000000 S rcuos/0
```

```shell
ps -elf
bad pid '-lef'
... ...

```

### SAMSUNG SM-G610F, Android 7.0

```shell
ps
USER      PID   PPID  VSIZE  RSS   WCHAN            PC  NAME
root      1     0     26128  744   SyS_epoll_ 00000000 S /init
root      2     0     0      0       kthreadd 00000000 S kthreadd
root      3     2     0      0     smpboot_th 00000000 S ksoftirqd/0
root      7     2     0      0     rcu_gp_kth 00000000 S rcu_preempt
root      8     2     0      0     rcu_gp_kth 00000000 S rcu_sched
root      9     2     0      0     rcu_gp_kth 00000000 S rcu_bh
root      10    2     0      0     smpboot_th 00000000 S migration/0
root      11    2     0      0     smpboot_th 00000000 S watchdog/0
root      12    2     0      0     smpboot_th 00000000 S watchdog/1
root      13    2     0      0     smpboot_th 00000000 S migration/1
root      14    2     0      0     smpboot_th 00000000 S ksoftirqd/1
root      17    2     0      0     smpboot_th 00000000 S watchdog/2
root      18    2     0      0     smpboot_th 00000000 S migration/2
root      19    2     0      0     smpboot_th 00000000 S ksoftirqd/2
root      22    2     0      0     smpboot_th 00000000 S watchdog/3
```

```shell
ps -lef
bad pid '-lef'
... ...

```

**Comment by sorccu** [comment]
Rather than checking the version, I think we should run with -lef first, then if it errors out try ps. Although maybe that could just be a single shell command  w/ some extra handling.

**Comment by thinkhy** [comment]
@sorccu Thanks for your suggestion. One liner command "ps -lef||ps" can handle the problem. I will push the improved solution to the patch.

**Comment by thinkhy** [comment]
After testing the commands "ps" and "ps -lef" on 100+ devices covering 30+ brands, from 4.0 ~ 8.1, I found the output is depend on ROM and Android version. I collected some cases below.

### Android version < 7.0

```shell
shell@msm8226:/ $ ps
USER     PID   PPID  VSIZE  RSS     WCHAN    PC         NAME
root      1     0     680    540   ffffffff 00000000 S /init
root      2     0     0      0     ffffffff 00000000 S kthreadd
root      3     2     0      0     ffffffff 00000000 S ksoftirqd/0
root      4     2     0      0     ffffffff 00000000 S kworker/0:0
root      5     2     0      0     ffffffff 00000000 S kworker/0:0H
root      6     2     0      0     ffffffff 00000000 D kworker/u:0
root      7     2     0      0     ffffffff 00000000 D kworker/u:0H
root      8     2     0      0     ffffffff 00000000 S migration/0
root      21    2     0      0     ffffffff 00000000 S khelper
root      22    2     0      0     ffffffff 00000000 S netns
root      23    2     0      0     ffffffff 00000000 S kworker/0:1
root      27    2     0      0     ffffffff 00000000 S kworker/0:1H
root      28    2     0      0     ffffffff 00000000 S modem_notifier
root      29    2     0      0     ffffffff 00000000 S smd_channel_clo
```

```shell
shell@msm8226:/ $ ps -lef
USER     PID   PPID  VSIZE  RSS     WCHAN    PC         NAME
```


### 7.0 <= Android version > 8.0

```shell
QK1801:/ $ ps
USER      PID   PPID  VSIZE  RSS   WCHAN              PC  NAME
root      1     0     17516  2788           0 0000000000 S /init
root      2     0     0      0              0 0000000000 S kthreadd
root      3     2     0      0              0 0000000000 S ksoftirqd/0
root      7     2     0      0              0 0000000000 S rcu_preempt
root      8     2     0      0              0 0000000000 S rcu_sched
root      9     2     0      0              0 0000000000 S rcu_bh
root      10    2     0      0              0 0000000000 S migration/0
root      11    2     0      0              0 0000000000 S migration/1
root      12    2     0      0              0 0000000000 S ksoftirqd/1
root      14    2     0      0              0 0000000000 S kworker/1:0H
```

```shell
QK1801:/ $ ps -lef
bad pid '-lef'
```


### Android version >= 8.0, Manufactor: Google, Huawei, XiaoMi, Oppo, output is like below.

```shell
ps
USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME                       
shell        15491  1137   10204   2056 0          7f8007a898 R ps
```

```shell
ps -elf
UID            PID  PPID C STIME TTY          TIME CMD
root             1     0 0 03:08:24 ?     00:00:21 init
root             2     0 0 03:08:24 ?     00:00:00 [kthreadd]
root             3     2 0 03:08:24 ?     00:03:52 [ksoftirqd/0]
root             7     2 0 03:08:24 ?     00:00:26 [rcu_preempt]
root             8     2 0 03:08:24 ?     00:00:00 [rcu_sched]
root             9     2 0 03:08:24 ?     00:00:00 [rcu_bh]
root            10     2 0 03:08:24 ?     00:00:38 [rcuop/0]
root            11     2 0 03:08:24 ?     00:00:00 [rcuos/0]
root            12     2 0 03:08:24 ?     00:00:00 [rcuob/0]
... ...
```

```shell
ps -elf|grep stf
shell         3936  1137 0 03:09:07 pts/0 00:00:00 stf.agent
u0_a149       4086   629 0 03:09:08 ?     00:00:00 jp.co.cyberagent.stf
shell        15502  1137 4 20:15:11 pts/4 00:00:00 sh -c ps -elf|grep stf
shell        15505 15502 9 20:15:11 pts/4 00:00:00 grep stf
``

### Oneplus3T - Android 8.0

```shell
OnePlus3T:/ $ ps -lef
UID            PID  PPID C STIME TTY          TIME CMD
root             1     0 0 36:17 ?        00:00:10 init
root             2     0 0 36:17 ?        00:00:00 [kthreadd]
root             3     2 0 36:17 ?        00:04:56 [ksoftirqd/0]
root             6     2 0 36:17 ?        00:00:00 [kworker/u8:0]
root             7     2 0 36:17 ?        00:04:18 [rcu_preempt]
root             8     2 0 36:17 ?        00:00:11 [rcu_sched]
root             9     2 0 36:17 ?        00:00:00 [rcu_bh]
root            10     2 0 36:17 ?        00:01:53 [rcuop/0]
root            11     2 0 36:17 ?        00:00:05 [rcuos/0]
root            12     2 0 36:17 ?        00:00:00 [rcuob/0]
root            13     2 0 36:17 ?        00:00:43 [migration/0]
root            14     2 0 36:17 ?        00:00:22 [migration/1]
... ...
```

```shell
OnePlus3T:/ $ ps
USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME
root             1     0   18896   3280 SyS_epoll+          0 S init
root             2     0       0      0 kthreadd            0 S [kthreadd]
root             3     2       0      0 smpboot_t+          0 S [ksoftirqd/0]
root             6     2       0      0 diag_sock+          0 S [kworker/u8:0]
root             7     2       0      0 rcu_gp_kt+          0 S [rcu_preempt]
root             8     2       0      0 rcu_gp_kt+          0 S [rcu_sched]
root             9     2       0      0 rcu_gp_kt+          0 S [rcu_bh]
root            10     2       0      0 nocb_lead+          0 S [rcuop/0]
root            11     2       0      0 nocb_lead+          0 S [rcuos/0]
root            12     2       0      0 nocb_lead+          0 S [rcuob/0]
root            13     2       0      0 smpboot_t+          0 S [migration/0]
root            14     2       0      0 smpboot_t+          0 S [migration/1]
... ...

So I changed the code to run 'ps' first(for most of devices it will work), then if it doesn't find the target process try 'ps -elf'.

@sorccu please review my code. Thanks.

**Comment by sorccu** [comment]
I think this patch will function, but I see one potential issue. In (probably) most cases, it's not going to find a process even if `ps` alone works, simply because the process isn't running. Then it unnecessarily runs `ps -lef` which of course fails. Therefore I think the current fallback logic is a bit flawed, since it runs that extra command. It should be able to tell that it saw correct output, but there were no matches, and only run the fallback if there was no output whatsoever.

Also, I think maybe `ps -lef` should be changed to `ps -lef 2>/dev/null`. Maybe `ps` too since some devices like to output weird errors everywhere, and it could mess up things.

**Comment by thinkhy** [comment]
@sorccu on Android 8.0  it's not going to find a process with 'ps' when  the process isn't running OR the process is not attached to current terminal's PTY. So we can't give up running the extra command 'ps -lef' just because ps works and there were no matches in the output. Consider the following case(Android version >= 8.0, Manufactor: Google, Huawei, XiaoMi, Oppo).:

```shell
ps
USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME                       
shell        15491  1137   10204   2056 0          7f8007a898 R ps
ps -elf
UID            PID  PPID C STIME TTY          TIME CMD
root             1     0 0 03:08:24 ?     00:00:21 init
root             2     0 0 03:08:24 ?     00:00:00 [kthreadd]
root             3     2 0 03:08:24 ?     00:03:52 [ksoftirqd/0]
root             7     2 0 03:08:24 ?     00:00:26 [rcu_preempt]
root             8     2 0 03:08:24 ?     00:00:00 [rcu_sched]
root             9     2 0 03:08:24 ?     00:00:00 [rcu_bh]
root            10     2 0 03:08:24 ?     00:00:38 [rcuop/0]
root            11     2 0 03:08:24 ?     00:00:00 [rcuos/0]
root            12     2 0 03:08:24 ?     00:00:00 [rcuob/0]
... ...
```

In above case, both 'ps' and 'ps -lef' can run well, but we cant only find STF related processes thru 'ps -lef'.

I will add '2>/dev/null' in next commit. Thanks for your reviewing.

**Comment by sorccu** [comment]
Yes, but I meant that it should try to detect whether the command ran successfully. I'm ok with running both on Android 8.0, but they both run on older versions as well if there's no match.

So for example, let's say the output is:

```
OnePlus3T:/ $ ps
USER           PID  PPID     VSZ    RSS WCHAN            ADDR S NAME
root             1     0   18896   3280 SyS_epoll+          0 S init
root             2     0       0      0 kthreadd            0 S [kthreadd]
root             3     2       0      0 smpboot_t+          0 S [ksoftirqd/0]
root             6     2       0      0 diag_sock+          0 S [kworker/u8:0]
root             7     2       0      0 rcu_gp_kt+          0 S [rcu_preempt]
root             8     2       0      0 rcu_gp_kt+          0 S [rcu_sched]
root             9     2       0      0 rcu_gp_kt+          0 S [rcu_bh]
```

And we were looking for `minicap`. Obviously, the output is correct, and the `ps` command has worked. However, we don't find `minicap` because it's not running. With the current logic, it will attempt to run `ps -lef` even though `ps` worked fine, it just didn't find anything.

**Comment by sorccu** [comment]
Basically, it should be able to detect three different scenarios:

1. Found matching process(es) → End here
2. Got an empty list, found no processes of any kind whatsoever → Try again with `ps -lef`
3. Got a non-empty list, but did not find any matching process → End here

**Comment by thinkhy** [comment]
OK, gotcha. Current code has already support scenario 1 and scenario 2:
    
   1. Found matching process(es) → End here
   2. Got an empty list, found no processes of any kind whatsoever → Try again with ps -lef

For scenario 3, suggest to divide it into two cases:    
   3. Got a non-empty list, but did not find any matching process 
       * 3.1 list contains any process launched by root user which suggests 'ps' can output the whole process list  → End here 
       * 3.2 list just contains processes launched by non-root user which suggests 'ps' might only output processes in current terminal  → Try again with ps -lef

**Pull request merged**
