### PR TITLE
Fix #117

### LINKED ISSUE #117: Units start before database is ready (stf local)
I consistently getting this when running `stf local`

```
FTL/reaper 7584 [reaper001] Unable to load initial state { [ReqlOpFailedError: Index `present` was not found on table `stf.devices` in:
r.table("devices").getAll(true, {index: "present"})
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^]
  name: 'ReqlOpFailedError',
  msg: 'Index `present` was not found on table `stf.devices`.',
  frames: [],
  message: 'Index `present` was not found on table `stf.devices` in:\nr.table("devices").getAll(true, {index: "present"})\n^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^' }
```

Manually adding the index to the table fixed the problem.

Apparently `migrate` cli already exit before the index was fully created.

### PR DESCRIPTION
**Pull request by neofreko**
indexWait does not report actual availability of index form query so we need to use actual query to verify an index is actually ready.

We need to process simple indexes (index with no indexFunction option) first before processing the complex indexes (which may be dependent to simple indexes).

Example log:
INF/db 24299 [*] Connecting to 127.0.0.1:28015
INF/db:setup 24299 [*] Database "stf" created
INF/db:setup 24299 [*] Table "vncauth" created
INF/db:setup 24299 [*] Processing simple indexes [ 'response' ]
INF/db:setup 24299 [*] Table "devices" created
INF/db:setup 24299 [*] Processing simple indexes [ 'present' ]
INF/db:setup 24299 [*] Table "users" created
INF/db:setup 24299 [*] Processing simple indexes []
INF/db:setup 24299 [*] Processing non-simple indexes [ 'adbKeys' ]
INF/db:setup 24299 [*] Index "vncauth"."response" created
INF/db:setup 24299 [*] Index "devices"."present" created
INF/db:setup 24299 [*] Waiting for index "vncauth"."response"
INF/db:setup 24299 [*] Waiting for index "devices"."present"
INF/db:setup 24299 [*] Index "users"."adbKeys" created
INF/db:setup 24299 [*] Waiting for index "users"."adbKeys"
INF/db:setup 24299 [*] Table "logs" created
INF/db:setup 24299 [*] Index "devices"."present" is ready
INF/db:setup 24299 [*] Processing non-simple indexes [ 'owner', 'providerChannel' ]
INF/db:setup 24299 [*] Index "vncauth"."response" is ready
INF/db:setup 24299 [*] Processing non-simple indexes [ 'responsePerDevice' ]
INF/db:setup 24299 [*] Index "users"."adbKeys" is ready
INF/db:setup 24299 [*] Index "devices"."owner" created
INF/db:setup 24299 [*] Waiting for index "devices"."owner"
INF/db:setup 24299 [*] Index "vncauth"."responsePerDevice" created
INF/db:setup 24299 [*] Waiting for index "vncauth"."responsePerDevice"
INF/db:setup 24299 [*] Index "devices"."providerChannel" created
INF/db:setup 24299 [*] Waiting for index "devices"."providerChannel"
INF/db:setup 24299 [*] Index "devices"."owner" is ready
INF/db:setup 24299 [*] Index "vncauth"."responsePerDevice" is ready
INF/db:setup 24299 [*] Index "devices"."providerChannel" is ready

### CODE REVIEW

**Comment by sorccu** [comment]
@vbanthia researched this a bit in #166. Any chance you could attempt to verify his findings?

**Comment by vbanthia** [comment]
Adding it in my todo list.

**Comment by gunta** [comment]
@neofreko any update on the above?

**Comment by neofreko** [comment]
I finally solve this by upgrading rethinkdb to 2.2.1 (via brew)

**Comment by vbanthia** [comment]
Closing this PR as problem was in `rethinkdb`. Above problem will occur if you are using rethinkdb < 2.13

Now, you can run `stf doctor` command in order to confirm all the stf dependencies.

**Pull request closed without merging**
