### PR TITLE
Bump up 3.4.2

### PR DESCRIPTION
**Pull request by att55**
### Overview

STF 3.4.2 has released.
https://github.com/openstf/stf/releases/tag/v3.4.2

So, I think the version in package.json should be bumped up.

### CODE REVIEW

**Comment by koral--** [comment]
Sorry for the delay. I'm now working on CI and release process unification on all the repositories so I'm not merging any PRs now. I'll go back here ASAP.

**Comment by att55** [comment]
@koral-- All right! I appreciate your response. 😄

**Comment by koral--** [comment]
@att55 your PR looks good. However, this repository will be archived and won't be updated.
Sorry for the inconvenience.
stf npm package also won't be updated. The successor is @devicefarmer/stf but it will start from 3.4.3

**Comment by att55** [comment]
@koral-- I'm so sorry for my late reply.
And thank you for your kind explanation 🙆‍♂️

**Comment by att55** [comment]
I will close this PR.

**Pull request closed without merging**
