### PR TITLE
[WIP] renewal booking feature 

### PR DESCRIPTION
**Pull request by hogehoge-banana**
This is booking feature with new architecture. retry work for #101 .
#101 is too much behind. So now I'm coding from scratch.
I'll make divided PR for this as follow later.
- device plugin
- reserve unit
- booking ui

If you have better way for this work, please instruct me.
ex: make feature branch on your organizer repository. then I'll make PR for it.

### CODE REVIEW

**Comment by denis99999** [comment]
Is this booking feature under development or available from now ?

**Comment by denis99999** [comment]
I forked the master branch but I don't see the booking feature available through the UI, what branch I have to fork ?

**Comment by sorccu** [comment]
It's shown at the top of the pull request.

**Comment by denis99999** [comment]
sorry the booking-renew thanks..

**Comment by denis99999** [comment]
Sorry again it does not change anything with this branch (booking-renew), I don't see the booking feature available through the UI, I don't see any additional parameters available while launching STF, so please tell me what is the way to activate this feature ?

**Comment by sorccu** [comment]
Then it might not be finished yet.

**Comment by hogehoge-banana** [comment]
https://github.com/hogehoge-banana/stf/pull/3
I made sub task on my personal repository.

**Pull request closed without merging**
