### PR TITLE
Device Booking feature

### PR DESCRIPTION
**Pull request by hogehoge-banana**
# Overview

This is Device booking feature. You can book device schedule on device-list. then, device scheduler unit  set you to "owner" on the time. And reject other user if the device is busy. device scheduler will check device schedule per a minute.
# Note

You can book schedule from one hour later.

### CODE REVIEW

**Comment by hogehoge-banana** [comment]
device-list
booking-modal

**Comment by sorccu** [comment]
It will take time to review this PR because the it is so big.

**Comment by codeskyblue** [comment]
wow

**Comment by vbanthia** [comment]
:+1:

**Comment by hogehoge-banana** [comment]
Thanks for your reply. Because my English is no good Maybe some method name or some variable name is fishy. And actually, it need more test for actual business. I continue test and I'll fix if I found some problem.

**Comment by benjamin-m-kane** [comment]
Great work, I was looking at implementing this myself!!

**Comment by gunta** [comment]
Getting a `WARNING: Tried to load angular more than once.`
Be sure to not include angular again since its already in the global namespace.

**Comment by hogehoge-banana** [comment]
Thanks for check. I'll research it.

**Comment by ma3tk** [comment]
:+1: nice feature!

**Comment by sorccu** [comment]
I think I would do something like this instead of polling every minute. It's not necessarily the best way though. Also, make sure to read all the way to the end.

1. Add `lib/units/device/plugins/reserve.js`
2. In there, start listening for a `ReserveUpdateMessage`, and send a `ReserveUpdateRequestMessage` when the device worker loads (just a sample name)
3. `processor` receives it, loads the full schedule for that device from the database, and a `ReserveUpdateMessage` back to the device with the details
4. The device worker wait for the nearest reservation, if any.
    - By either setting a timeout for the nearest job - 10s, and then kicking out whoever is using the device (if anyone) and make the scheduled user the owner, `setTimeout()` isn't super accurate so it should trigger a bit earlier (and it won't do much harm)
    - OR perhaps instead of `setTimeout`, always have a `setInterval` running in the background in the device process (perhaps checked once per minute). When the callback triggers, check the internal state if the next reservation is closer than the next internal. If so, kick out current user and make the scheduled user the owner.
5. If a new reservation is made, send a new `ReserveUpdateMessage` with the full schedule to the device channel
    - Update internal in-memory state
    - Clear `setTimeout` or `setInterval`, run a check immediately, and set up new timers

Step 5 could be made easier if we handled messages from the application side in the processor. That way you could just send a tiny message to the processor and it would load and send a full `ReserveUpdateMessage` to the device channel. However since it's not possible right now, what you'd probably have to do is to create the full `ReserveUpdateMessage` in the `websocket` or `app` unit, and then send it as-is to the processor.

HOWEVER, I like having the reservation functionality completely separate from the device process like it is in your patch (reaper style). It makes it easier to manage. It would be best if you could adapt the steps in your `scheduler` unit instead. You could then even use RethinkDB's `.watch()` in the `scheduler` unit to load schedule changes in real time, and send `ReserveUpdateMessage` to appropriate devices when necessary. That you you wouldn't necessarily have to send a separate message from the `websocket` or `app` unit to the `scheduler` unit, it would automatically see all changes.

**Comment by hogehoge-banana** [comment]
Thanks for check. I'll follow them. It's similar to one of my other ideas.

**Comment by hogehoge-banana** [comment]
>2. In there, start listening for a ReserveUpdateMessage, and send a ReserveUpdateRequestMessage when the device worker loads (just a sample name)
>3. processor receives it, loads the full schedule for that device from the database, and a ReserveUpdateMessage back to the device with the details

You mean, I can "not" access to rethinkdb from  `device/plugins/reserve.js`  right?

**Comment by hogehoge-banana** [comment]
my idea is as follow images.
### On Device wake up.
on-wakeup-flow

### On update schedule.
on-update-flow

----
It can make completely separate this feature.

**Comment by tadesushilgithub** [comment]
How can I see this feature in installed STF? or Do I need to add this plugin separately?

**Comment by hogehoge-banana** [comment]
It's not ready yet. Sorry.

**Comment by tadesushilgithub** [comment]
@hogehoge-banana could you please tell me when would this be ready? (any tentative time )

**Comment by nhanvpt102** [comment]
Hi hogehoge-banana, 
Thanks very much for this nice feature.
I added your code and start STF but could not see the screen 'Book Device'. 
Would you please let me know if I missed something or how we can activate this feature?

**Comment by hogehoge-banana** [comment]
Hi, Thanks for check my code. While I'll research it, It will take time. Because Actually I left this project. Now, I just play "stf" on my private time.

**Comment by skumar1122** [comment]
Hey @hogehoge-banana , 

This is amazing feature for STF , is this ready yet ?
please let me know.

Thanks
SK

**Comment by hogehoge-banana** [comment]
@skumar1122
Not ready yet. Sorry.

**Comment by skumar1122** [comment]
@hogehoge-banana 
No worries !

**Comment by histronger** [comment]
> @skumar1122
> Not ready yet. Sorry.

Since it has been a long time, and have this feature finished?

**Comment by hogehoge-banana** [comment]
I’m sorry, but it’s not yet.

**Comment by skumar1122** [comment]
Hey @hogehoge-banana @sorccu 

I have a question, Can we use **stf** with admin rights. So that admin can maintain device usage. If its already exists please let me know ?

Thanks
Shiva

**Comment by asabhijitshelar** [comment]
Hey @hogehoge-banana @sorccu,

Is Device Booking feature is available in Stf version 3.4.1

**Comment by hogehoge-banana** [comment]
I think, it’s not available. There are big differences from I developed this feature.
I’m sorry. Currently I don’t have enough time to spend for this project.

**Comment by koral--** [comment]
This feature is not merged thus not available in any release.
However, there is a Group feature: https://github.com/openstf/stf/blob/master/doc/GroupFeature.pdf available on `latest` tag (not in 3.4.1).
I didn't follow this PR but it looks like these 2 features are partially overlapping.

**Comment by hogehoge-banana** [comment]
There are already good feature. So I close this pull request.
Thanks all.

**Pull request closed without merging**
