### PR TITLE
Screen reset option

### LINKED ISSUE #722: "Stop using" device cause minimising top activity application
Somehow connected to: #346 #242 
**What is the issue or idea you have?**

I've checked cli.js file and didn't found any flag that would be helpful.
When the session is closed ("stop using" option) for each device, the application which is on the top activity is closed (minimised).

Is there something that I've missed, flag or any other way to leave the application on the top after closing device session?

The case I'm thinking about:
Automated tests are running on the device (for example Espresso). While this is happening I would like to lookup on the device to check if everything is ok. But when I'm leaving the session ("stop using" option) the application is closed (minimised).

I would like that application to be still on top activity then I leave the device session to let the tests run without interruption.

### PR DESCRIPTION
**Pull request by 0rzech**
Adds option to control screen resetting when user releases device. Resolves #722.

### CODE REVIEW

**Comment by chickenbeef** [comment]
+1 for this feature please.

**Comment by sorccu** [comment]
Looks good but please put the commas in line with the existing ones. Some are a bit too intended right now. Some editors try to mess them up by default.

**Comment by 0rzech** [comment]
Yes, my editors and IDEs actively fight me with this formatting. Sorry for overlooking that.

PS. Could you take a look at #778 as well?

**Comment by sorccu** [comment]
Merged, sorry it took so long. Been very busy lately.

**Comment by 0rzech** [comment]
No problem and thank you for your work!

**Pull request merged**
